
project_id = "btrqtckxwvqkotnpyhgo"

[functions.fatsecret]
verify_jwt = false

[auth.external.google]
enabled = true
client_id = "enter-your-actual-google-client-id-here"
secret = "enter-your-actual-google-client-secret-here"

