// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btrqtckxwvqkotnpyhgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cnF0Y2t4d3Zxa290bnB5aGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTI1OTMsImV4cCI6MjA2MjE2ODU5M30.0NHV92_M7tfnJvcwo7Hk_bdwUWLVgH_8MhVWrUqGF-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);